# This is a basic workflow to help you get started with Actions

name: Build and upload

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies and build ETL
      - name: Install Dependencies and Build
        run: |
          sudo apt-get install -y nasm libwayland-dev wayland-protocols libgl1-mesa-dev libglu1-mesa-dev libasound2-dev pulseaudio libpulse-dev
          ./easybuild.sh -64

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: ${{ github.ref }}
          # The name of the release. For example, `Release v1.0.1`
          release_name: ${{ github.ref }}
          # Text describing the contents of the tag.
          #body: # optional
          # Path to file with information about the tag.
          #body_path: # optional
          # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
          draft: true
          # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
          prerelease: true
          # Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit
          #commitish: # optional
          # Owner of the repository if it is not the current one
          #owner: # optional
          # Repository on which to release.  Used only if you want to create the release on another repo
          #repo: # optional
      - name: Upload a Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # The URL for uploading assets to the release
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # The path to the asset you want to upload
          asset_path: /home/runner/work/etlegacy-1/etlegacy-1/build/etlegacy-2.76-dirty-x86_64.tar.gz
          # The name of the asset you want to upload
          asset_name: etlegacy-2.76-dirty-x86_64.tar.gz
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: application/gzip
          
