name: ETLBuild

on: [ push ]

jobs:
  lnx32:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install nasm gcc-multilib g++-multilib
          sudo apt install libwayland-dev:i386 wayland-protocols libgl1-mesa-dev:i386 libglu1-mesa-dev:i386
          sudo apt install libasound2-dev:i386 pulseaudio:i386 libpulse-dev zlib1g-dev:i386 libsnappy-dev:i386 liblz4-1:i386
      - name: Build
        shell: bash
        run: ./easybuild.sh -32

      - uses: actions/upload-artifact@v2
        with:
           name: lnx64-package
           path: /home/runner/work/etlegacy-1/etlegacy-1/build/etlegacy-2.76-dirty-x86_64.tar.gz
        
  lnx64:
     runs-on: ubuntu-16.04
     steps:
       - uses: actions/checkout@v2
       - name: Install dependencies
         run: |
           sudo apt update
           sudo apt install nasm libwayland-dev wayland-protocols libgl1-mesa-dev libglu1-mesa-dev libasound2-dev pulseaudio libpulse-dev
 
       - name: Build
         shell: bash
         run: ./easybuild.sh -64
       
       - uses: actions/upload-artifact@v2
         with:
            name: lnx64-package
            path: /home/runner/work/etlegacy-1/etlegacy-1/build/etlegacy-2.76-dirty-x86_64.tar.gz
         
  osx:
     runs-on: macos-10.15
     steps:
       - uses: actions/checkout@v2
       - name: Install dependencies
         run: brew bundle
 
       - name: Build
         env:
           DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
         shell: bash
         run: ./easybuild.sh -64 --osx=10.14
         
       - uses: actions/upload-artifact@v2
         with:
            name: osx-package
            path: /home/runner/work/etlegacy-1/etlegacy-1/build/etlegacy-2.76-dirty-x86_64.tar.gz
 
  win:
     runs-on: windows-2019
     steps:
       - uses: actions/checkout@v2

       - name: Build
         shell: cmd
         run: call .\easybuild.bat

       - uses: actions/upload-artifact@v2
         with:
            name: win-package
            path: /home/runner/work/etlegacy-1/etlegacy-1/build/etlegacy-2.76-dirty-x86_64.tar.gz
